spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/tasks
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

minio:
  initialize-bucket: ${MINIO_INITIALIZE_BUCKET:true}
